#!/usr/bin/env python

import argparse
import os
import re
import sys

argparser = argparse.ArgumentParser()
argparser.add_argument("input", nargs="?")

args = argparser.parse_args()

input_ = args.input
if input_ == "-":
    input_ = None

if input_:
    data = input_
    if os.path.exists(data):
        with open(data, "rt") as fp:
            data = fp.read()
else:
    data = sys.stdin.read()

def replacer(m):
    v = m.group(2)

    v = chr(int(v, 16))

    return v

data = re.sub(r"(\\u[{]([a-z0-9]+?)[}])", replacer, data)
data = re.sub(r"(\\x([a-z0-9]{2}))", replacer, data, flags=re.I)

sys.stdout.write(data)
